// src/app/layout.tsx
import './globals.css';
// import type { Metadata } from 'next'; // <--- ¡COMENTAR O ELIMINAR ESTA LÍNEA!
import { ClerkProvider } from '@clerk/nextjs';
import Header from '@/components/Header'; // Asegúrate de que Header.tsx exista y tenga la capitalización correcta
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

// La Metadata se define aquí, pero el tipo 'Metadata' no se usa directamente en el componente
// export const metadata: Metadata = { // Si usas esto, no se marcará como no usada
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider unsafe_disableDevelopmentModeWarnings> {/* Added the prop here */}
      <html lang="en">
        <body className={inter.className}>
          <Header />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
